### PR TITLE
Save dark mode in localstorage.

### PR DESCRIPTION
**Pull request by mollthecoder**
This makes it so that dark mode can persist across sessions.
(Note: Accidentally broke something, I'm drafting until fixed)

### CODE REVIEW

**Comment by mollthecoder** [comment]
Fixed

**Comment by BobTheBirdCodar** [comment]
Thanks!

Let me test it before putting it on the main branch.

**Comment by mollthecoder** [comment]
Oops it's broken. Let me fix it.

**Comment by mollthecoder** [comment]
Fixed

**Comment by mollthecoder** [comment]
It's still broken

**Comment by mollthecoder** [comment]
This is a pain

**Comment by mollthecoder** [comment]
I don't know why it won't work. I'm closing so it can be implemented some other time.

**Comment by BobTheBirdCodar** [comment]
I'm opening it so I can look at it more.

**Comment by BobTheBirdCodar** [comment]
I fixed it!

**Pull request merged**
